[theme]
# Custom theme colors to match real estate/professional look
primaryColor = "#FF4B4B"  # Accent color for interactive elements
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for sidebar/widgets
textColor = "#262730"  # Dark gray for text

[server]
# Security settings
enableCORS = false
enableXsrfProtection = true
port = 8501  # Matches your dev_resources.py port configuration
fileWatcherType = "auto"

[browser]
# Disable usage statistics
gatherUsageStats = false

[runner]
# Optimize for real estate app performance
magicEnabled = true
fastReruns = true

[client]
# Error handling and toolbar settings
showErrorDetails = true
toolbarMode = "auto"

[logger]
# Match your logging configuration from Home.py
level = "warning"
messageFormat = "%(message)s"